apiVersion: v1
kind: Pod
metadata:
  name: pod-tarefas
  labels:
    app: api-tarefas
spec:
  containers:
  - name: api-container
    image: teixeiraalexandre/devops-api:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80