apiVersion: v1
kind: Pod
metadata:
  name: pod-tarefas
  labels:
    app: api-tarefas
spec:
  containers:
  - name: api-container
    image: python:3.12
    command: ["/bin/sh", "-c"]
    args:
    - curl -sO https://raw.githubusercontent.com/Disnerxx/DevOps-Entrega02/main/main.py && pip install "fastapi[standard]" uvicorn && uvicorn main:app --host 0.0.0.0 --port 80
    ports:
    - containerPort: 80