name: Pipeline DevOps - CI/CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  integracao_continua:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python no servidor do GitHub
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependências da aplicação
      run: |
        python -m pip install --upgrade pip
         pip install -r requirements.txt

    - name: Executar os testes unitários (pytest)
      run: |
        pytest test_main.py

  entrega_continua:
    needs: integracao_continua
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e push da imagem
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-api:${{ github.sha }}